services:
  api:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://temp:temp@db:5432/takehome
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=temp
      - POSTGRES_USER=temp
      - POSTGRES_DB=takehome
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
