[project]
name = "veryfi-takehome"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "ijson>=3.3.0",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.39",
]
